### ISSUE TITLE
远程计算机拒绝网络连接？

### ISSUE THREAD

**Issue by 9LX9** [JezaChen/SSEPy#24]
![Uploading 图片1.png…]()

**Comment by JezaChen** [comment]
![image](https://github.com/JezaChen/SSEPy/assets/31545780/49caf632-2a0b-40ce-a3f1-5e9fa583b5e3)

请详细描述问题，另外你那个图片还没上传完毕就comment了，我不清楚你所表达的内容。

**Comment by 9LX9** [comment]
![图片1](https://github.com/JezaChen/SSEPy/assets/138541351/f642b014-c0b9-425f-9eab-c222ca27b892)
请问这个是什么原因

**Comment by 9LX9** [comment]
![image](https://github.com/JezaChen/SSEPy/assets/138541351/71eef8e7-265e-4390-96ef-9f679b7973d8)
请问运行服务器时一直显示这个样子是什么问题呀

**Comment by JezaChen** [comment]
这个没问题的，你按README的步骤，另外创建一个终端，继续运行客户端的程序`run_client.py`就好了。

当客户端上传配置文件完毕后，`run_server.py`那边也会有日志输出的。

![image](https://github.com/JezaChen/SSEPy/assets/31545780/d573ff03-ef2d-4b9a-a2f5-96142161a7af)

**Comment by 9LX9** [comment]
你好，上传配置文件的时候出现了才开始我问的那个问题，就是远程计算机拒绝网络连接的那个图片，这个是因为什么呢

**Comment by 9LX9** [comment]
哦~我知道了，非常感谢！！！

**Comment by JezaChen** [comment]
麻烦在`global_config.py`里面将`ClientConfig.CONSOLE_LOG_LEVEL`设置为`logging.INFO`再跑一遍看看

**Comment by JezaChen** [comment]
诶，什么错误~

**Comment by 9LX9** [comment]
是因为把服务器终端关掉了，所以显示拒接网络连接

**Comment by JezaChen** [comment]
嗯嗯，这个需要服务端一直运行的，之前没弄后台逻辑，后面毕业也没时间继续搞(•̀ᴗ• )
